# Generated by Django 2.0.5 on 2018-08-26 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photosite', '0003_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.AddField(
            model_name='favorites',
            name='title',
            field=models.CharField(default=models.CharField(max_length=512), max_length=32),
        ),
        migrations.AddField(
            model_name='favorites',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='photo',
            field=models.CharField(max_length=512),
        ),
    ]
