# Generated by Django 2.0.5 on 2018-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0004_auto_20180826_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='photo',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='title',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
