# Generated by Django 2.0.5 on 2018-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0005_auto_20180826_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='title',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
