# Generated by Django 2.1.2 on 2018-10-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0006_auto_20180826_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relpath', models.CharField(max_length=512)),
                ('title', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
    ]
