# Generated by Django 2.1.2 on 2018-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='relpath',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
